language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-26.1.0
    - android-26
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services

script:
  - ./gradlew assembleDebug

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: "app/build/outputs/apk/app-debug.apk"
  skip_cleanup: true
  on:
    tags: true
    branch: master

notifications:
    email: false
